# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-02 12:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_building_max_booking_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 2, 12, 0, 24, 181745, tzinfo=utc), verbose_name=b'Letzte Aktualisierung'),
            preserve_default=False,
        ),
    ]
