# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-19 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_building_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='apartment',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name=b'Wohnung'),
        ),
    ]
